name: My First CI/CD Practice

on:
  push:
    branches:
      - main

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Get my code
        uses: actions/checkout@v4

      - name: Check index.html
        run: test -f index.html

      - name: Check HTML heading
        run: grep -q "<h1>" index.html

      - name: CI successful
        run: echo "HTML checks passed successfully!"

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
           name: website
           path: index.html 
